providers:
  alibaba:
    region_id: region_id
    access_key_id: access_key
    access_key_secret: access_secret
    template_code: template_code
  netease:
    api_key: api_key
    api_secret: api_secret
receivers:
  - name: test1
    provider: xxx123dasd
    to:
      - 1333333
      - 1444444
  - name: test2
    provider: netease
    to:
      - 233333
      - 244444
      - dasda
